ci:
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate [ci skip]"
  skip: [shellcheck]

default_language_version:
  python: python3.14

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: trailing-whitespace

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: 4b2e70d08cb2ccd26d1fba73588de41c7a5d50b7 # frozen: v0.25
    hooks:
      - id: validate-pyproject
        additional_dependencies:
          - validate-pyproject-schema-store[all]>=2025.11.14

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: b831c3dc5d27d9da294ae4e915773b99aa24a7c5 # frozen: v0.15.10
    hooks:
      - id: ruff-check
        args: ["--fix", "--show-fixes", "--unsafe-fixes"]
      - id: ruff-format

  - repo: https://github.com/codespell-project/codespell
    rev: 2ccb47ff45ad361a21071a7eedda4c37e6ae8c5a # frozen: v2.4.2
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
        args: ["--ignore-words-list=lief,LIEF", "-w", "--skip=*.rtf"]

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: d730ad6820486029c4fd4cd291a6461a0b6501a3 # frozen: v22.1.3
    hooks:
      - id: clang-format
        exclude: (?x)^(src/msilib/include/pythoncapi_compat.h)$
        types_or: [c, c++]

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: c2bc67fe8f8f549cc489e00ba8b45aa18ee713b1 # frozen: v3.8.1
    hooks:
      - id: prettier
        types_or: [yaml, markdown, html, css, scss, javascript, json]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: 745eface02aef23e168a8afb6b5737818efbea95 # frozen: v0.11.0.1
    hooks:
      - id: shellcheck

  - repo: local
    hooks:
      - id: pythoncapi
        name: upgrade pythoncapi
        entry: ci/pythoncapi.sh
        language: unsupported
        files: ^(
          src/msilib/include/pythoncapi_compat.h|
          src/msilib/include/.*.h|src/msilib/.*.c)$

  - repo: local
    hooks:
      - id: requirements
        name: requirements
        language: system
        entry: python ci/requirements.py
        files: ^(pyproject.toml|requirements.txt|requirements-dev.txt|
          tests/requirements.txt
          )$
