name: Command

on:
  issue_comment:
    types: [created]

concurrency:
  group: pypi-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  publish:
    name: Publish package to TestPyPI
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/testpypi')
    environment:
      name: ${{ github.event_name }}
      url: https://test.pypi.org/p/python-msilib
    permissions:
      id-token: write # MANDATORY: Required for OIDC Trusted Publishing
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Download all artifacts
        uses: dawidd6/action-download-artifact@d63b86af1b34672e53c440b1b83979861906bad7 # v24
        with:
          workflow: ci.yml
          pr: ${{ github.event.issue.number }}
          name: python-msilib-wheel-* # pattern
          name_is_regexp: true
          path: wheelhouse
          merge_multiple: true # merge-multiple: true
          workflow_conclusion: success

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
        with:
          packages-dir: wheelhouse/
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
          verbose: true
